// src/data/products.js

export const products = [
  {
    id: 1,
    name: "Azure Breeze - Premium Lawn",
    price: 4500,
    currency: "BDT",
    category: "Lawn",
    type: "Unstitched",
    fabric: "Swiss Lawn",
    image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?q=80&w=1000&auto=format&fit=crop",
    description: "Digital printed premium lawn shirt with chiffon dupatta.",
    isNew: true,
  },
  {
    id: 2,
    name: "Crimson Velvet Luxe",
    price: 8500,
    currency: "BDT",
    category: "Velvet",
    type: "Stitched",
    fabric: "Micro Velvet",
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop",
    description: "Embroidered neckline with jamawar trousers.",
    isNew: false,
  },
  {
    id: 3,
    name: "Ivory Silk Festivity",
    price: 12000,
    currency: "BDT",
    category: "Silk",
    type: "Unstitched",
    fabric: "Raw Silk",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop",
    description: "Hand-embellished raw silk kameez with organza dupatta.",
    isNew: true,
  },
  {
    id: 4,
    name: "Pastel Floral Organza",
    price: 6200,
    currency: "BDT",
    category: "Organza",
    type: "Stitched",
    fabric: "Pure Organza",
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop",
    description: "Floral aesthetic with lace detailing.",
    isNew: false,
  },
];